name: Flutter CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_VERSION: "3.3.10"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1.5.1
        with:
          flutter-version: "3.7.6"

      - name: Pub Get Packages
        run: |
          flutter pub get
          
      - name: Test Flutter
        run: |
          flutter test
